### ISSUE TITLE
Problem to install ntsynt with conda

### ISSUE THREAD

**Issue by Enorya** [bcgsc/ntSynt#45]
Dear,

I'm trying to install ntsynt using conda but I keep getting the following error when I use `conda install -c bioconda -c conda-forge ntsynt`:
```
Collecting package metadata (repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 122, in do_call
        return getattr(module, func_name)(args, parser)
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/site-packages/conda/notices/core.py", line 121, in wrapper
        return func(*args, **kwargs)
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/site-packages/conda/cli/install.py", line 264, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 134, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 177, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 282, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/site-packages/conda/common/io.py", line 84, in decorated
        return f(*args, **kwds)
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 449, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 1064, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/site-packages/conda/core/index.py", line 267, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 169, in query_all
        result = tuple(chain.from_iterable(executor.map(subdir_query, channel_urls)))
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
        yield _result_or_cancel(fs.pop())
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
        return fut.result(timeout)
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 451, in result
        return self.__get_result()
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
        raise self._exception
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 158, in subdir_query
        return tuple(
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 174, in query
        self.load()
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 264, in load
        _internal_state = self._load()
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 315, in _load
        cache.load_state()  # XXX should this succeed even if FileNotFound?
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 570, in load_state
        self.load(state_only=True)
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 528, in load
        state = json.loads(state_file.read())
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/data/leuven/340/vsc34088/miniconda3/lib/python3.10/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ /data/leuven/340/vsc34088/miniconda3/bin/conda install -c bioconda -c conda-forge ntsynt`
```
When I try to install other conda packages it works so the problem doesn't seem to come from the environment I'm working in.

Can you help me with this issue?

Thank you in advance for your help.
Best regards

**Comment by Enorya** [comment]
Hi @lcoombe ,

Thank you for your help! 
I followed the suggestions at the link you provided and using `conda clean --all` solved the isuue.

Thanks again!
Enora

**Comment by lcoombe** [comment]
Excellent, I'm so glad to hear that fixed it for you!
